# Copyright 2026 Jordy Slagter
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: release_document_template

on:
  push:
    branches:
      - "main"
    paths:
      - "zuydfacilitymanagement/**"
  workflow_dispatch:

permissions:
  contents: write # REQUIRED for creating releases

jobs:
  release:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate timestamp
        id: ts
        run: echo "value=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

      - name: Zip directory
        id: zip
        run: |
          DIR="zuydfacilitymanagement"
          ZIP_NAME="${DIR}-${{ steps.ts.outputs.value }}.zip"

          cp LICENSE "$DIR/"

          zip -r "$ZIP_NAME" "$DIR"

          echo "name=$ZIP_NAME" >> $GITHUB_OUTPUT

      - name: Create Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ steps.ts.outputs.value }}" \
            "${{ steps.zip.outputs.name }}" \
            --title "Release ${{ steps.ts.outputs.value }}" \
            --notes "Automated release"
